reset_avg_year:
  name: Reset average year
  description: Reset the "avg year" sensor(s) to 0 and set their year to the current year.
  fields:
    entity_id:
      name: Entity
      description: One or more "avg year" sensor entity IDs to reset. If omitted, all "avg year" sensors are reset.
      required: false
      example: sensor.solardelta_my_device_avg_year

reset_avg_lifetime:
  name: Reset average lifetime
  description: Reset the "avg lifetime" sensor(s) to 0.
  fields:
    entity_id:
      name: Entity
      description: One or more "avg lifetime" sensor entity IDs to reset. If omitted, all "avg lifetime" sensors are reset.
      required: false
      example: sensor.solardelta_my_device_avg_lifetime
